spring.application.name=saveslot

spring.datasource.url=jdbc:postgresql://localhost:5432/saveslot
spring.datasource.username=saveslot
spring.datasource.password=saveslot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration
spring.jpa.defer-datasource-initialization=true

